db.raters.ensureIndex({ "name": 1 }, { unique: true });
db.ratings.ensureIndex({ "artist": 1, "rater": 1}, {unique: true});
db.artists.ensureIndex({ "name": 1 }, { unique: true });
db.artists.save({ "name" : "Samir & Viktor", "songName" : "Groupie", "startNumber" : 1, "ratings": [] });
db.artists.save({ "name" : "JTR", "songName" : "Building It Up", "startNumber" : 2, "ratings": [] });
db.artists.save({ "name" : "Dinah Nah", "songName" : "Make Me (La La La)", "startNumber" : 3, "ratings": [] });
db.artists.save({ "name" : "Jon Henrik Fjällgren", "songName" : "Jag är fri (Manne Leam Frijje)", "startNumber" : 4, "ratings": [] });
db.artists.save({ "name" : "Jessica Andersson", "songName" : "Can't Hurt Me Now", "startNumber" : 5, "ratings": [] });
db.artists.save({ "name" : "Måns Zelmerlöw", "songName" : "Heroes", "startNumber" : 6, "ratings": [] });
db.artists.save({ "name" : "Linus Svenning", "songName" : "Forever Starts Today", "startNumber" : 7, "ratings": [] });
db.artists.save({ "name" : "Isa", "songName" : "Don't Stop", "startNumber" : 8, "ratings": [] });
db.artists.save({ "name" : "Magnus Carlsson", "songName" : "Möt mig i Gamla Stan", "startNumber" : 9, "ratings": [] });
db.artists.save({ "name" : "Eric Saade", "songName" : "Sting", "startNumber" : 10, "ratings": [] });
db.artists.save({ "name" : "Mariette", "songName" : "Don't Stop Believing", "startNumber" : 11, "ratings": [] });
db.artists.save({ "name" : "Hasse Andersson", "songName" : "Guld och gröna skogar", "startNumber" : 12, "ratings": [] });
